name: flutterfire_samples
description: Firebase + Flutter sample apps with code snippets, supported by comprehensive articles for each implementation.

publish_to: "none"
version: 2.6.0+10

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  google_sign_in: ^5.2.4
  cloud_firestore: ^3.1.10
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 500
        - asset: fonts/OpenSans-Bold.ttf
          weight: 600
        - asset: fonts/OpenSans-ExtraBold.ttf
          weight: 700
